services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - task-manager-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - task-manager-net
    depends_on:
      - backend

networks:
  task-manager-net:
    driver: bridge
